export enum ActionType {
  CORE_RESET_STATE = "CORE_RESET_STATE",
  CORE_LOADER = "CORE_LOADER",

  ADMIN_WIDGET_GETPAGEASYNC = "ADMIN_WIDGET_GETPAGEASYNC",
  ADMIN_WIDGET_GETITEMASYNC = "ADMIN_WIDGET_GETITEMASYNC",
  ADMIN_WIDGET_SAVEASYNC = "ADMIN_WIDGET_SAVEASYNC",
  ADMIN_WIDGET_SETPAGE = "ADMIN_WIDGET_SETPAGE",
  ADMIN_WIDGET_SETITEM = "ADMIN_WIDGET_SETITEM"
}