export enum AsyncActions {
  CONFIG_WIDGET_GETPAGEASYNC = "CONFIG_WIDGET_GETPAGEASYNC",
  CONFIG_WIDGET_GETITEMASYNC = "CONFIG_WIDGET_GETITEMASYNC",
  CONFIG_WIDGET_SAVEASYNC = "CONFIG_WIDGET_SAVEASYNC",

  COMMON_AUTH_LOGINASYNC = "COMMON_AUTH_LOGINASYNC",
}

export enum SyncActions {
  CORE_RESET_STATE = "CORE_RESET_STATE",
  CORE_LOADER = "CORE_LOADER",

  CONFIG_WIDGET_SETPAGE = "CONFIG_WIDGET_SETPAGE",
  CONFIG_WIDGET_SETITEM = "CONFIG_WIDGET_SETITEM",

  COMMON_AUTH_SETFORM = "COMMON_AUTH_SETFORM",
  COMMON_AUTH_SETAUTHINFO = "COMMON_AUTH_SETAUTHINFO"
}